apiVersion: apps/v1
kind: Deployment

metadata:
  name: money-tracker-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: money-tracker

  template:
    metadata:
      labels:
        app: money-tracker

    spec:
      containers:
      - name: money-tracker
        image: shalmadsouza/money-tracking:v1
        imagePullPolicy: Always
